### ISSUE TITLE
Movie Explorer forgets preferences

### ISSUE THREAD

**Issue by Haye1982** [anlarke/MovieExplorer#29]
I first want to say that I love this program, thank you so much for creating it. I have a small issue though... It seems to forget my preferences.

I select the dark theme, the next time it opens it reverts ti the light theme. Also I "lost" about 350 movies. I realized it's because the extension "m4v" I added disappeared from the extensions list. Not a huge deal as I can switch to the dark theme and re-add the extension. I was just hoping for a permanent fix.

Keep up the good work!

Around 1600 movies / i5 3750K Quad Core / 8 gig RAM / Windows 7 64 bit

**Comment by ryanjay0** [comment]
Can the program write to the Preferences.xml file in the main program directory? Check it after you close the program to see if it writes correctly. I'll try to help fix this.
