### ISSUE TITLE
IMDbUseOriginalTitle doesn't work any longer

### ISSUE THREAD

**Issue by panta82** [anlarke/MovieExplorer#32]
It seems IMDb has changed their `html` which broke the scraper.

The html is now like this:

```html
<div class="originalTitle">Il buono, il brutto, il cattivo<span class="description"> (original title)</span></div>
```

The current regex is expecting the `<i>` tag:

```c++
if (bUseOriginalTitle)
	GetFirstMatch(str, _T(">[^<]*?\"([^<]*?)\"[^<]*?<i>\\(original title\\)</i>"),
		&pInfo->strTitle, NULL);
```

I would have updated the regex myself. Unfortunately, not being a C++ guy, I have utterly failed to get this project to compile in VS2015. :/

**Comment by ryanjay0** [comment]
Fixed! Thanks.

And i had a horrific time trying to get it to compile in VS2015 also. I couldn't ever get it to work with the 14.0 tools. I had to use the 12.0 tools in and remake the boost libraries also. That's all in the latest branch but here's an x64 binary for you.

[MovieExplorer.zip](https://github.com/anlarke/MovieExplorer/files/248346/MovieExplorer.zip)

**Comment by panta82** [comment]
Thanks a lot!

New version works great.
