### ISSUE TITLE
broken as of 07/29/2016

### ISSUE THREAD

**Issue by moviegrits** [anlarke/MovieExplorer#35]
IMDB API change?

**Comment by ryanjay0** [comment]
It seems to be working fine for me. Got an example?

Sent from Yahoo Mail on Android 
 
  On Fri, Jul 29, 2016 at 18:49, moviegrits<notifications@github.com> wrote:   
IMDB API change?

**Comment by moviegrits** [comment]
"An error occurred while scraping movie data."

Happened on about 30% of 140 movies. Reboot didn't help.

**Comment by ryanjay0** [comment]
I'm getting some of that too now even though it's mostly working. Let me look into it.

**Comment by ryanjay0** [comment]
new release just now works for me. let me know if you have more problems. thanks.
