### ISSUE TITLE
Cover's not showing.

### ISSUE THREAD

**Issue by Schoenherrr** [anlarke/MovieExplorer#36]
So, it goes through the entire update process when you start the program. Finds all the information about the movies, but shows no Cover Art. Tried both IMDB and MovieMeter. Cleared everything and reinstalled (latest version)

The Cache folder shows as normal, but all the jpeg files are empty (viewer can't open)

I'm running x64 Windows 10. Version 1511. OS Build 10586.589

Hopefully it's something that's fixable! This is my favorite program!

**Comment by ryanjay0** [comment]
I use it daily and see the same thing. It's been acting up for a month and I haven't been able to look at it yet. I'll get it fixed this week.

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 15, 2016 at 12:37, Schoenherrr<notifications@github.com> wrote:   
So, it goes through the entire update process when you start the program. Finds all the information about the movies, but shows no Cover Art. Tried both IMDB and MovieMeter. Cleared everything and reinstalled (latest version)

Hopefully it's something that's fixable! This is my favorite program!

**Comment by lrishJoe** [comment]
Thanks in advance for fixing, much appreciated!

**Comment by ryanjay0** [comment]
Fixed the cover issue. Working on the issue where either shows a bunch of empty unfound ones. Testing etc. 

Sent from Yahoo Mail on Android 
 
  On Sat, Sep 17, 2016 at 12:09, lrishJoe<notifications@github.com> wrote:   
Thanks in advance for fixing, much appreciated!

**Comment by ryanjay0** [comment]
Will push and release a new version soon.

Sent from Yahoo Mail on Android 
 
  On Sat, Sep 17, 2016 at 16:45, Ryan D<ryan.d831@yahoo.com> wrote:   Fixed the cover issue. Working on the issue where either shows a bunch of empty unfound ones. Testing etc. 

Sent from Yahoo Mail on Android 
 
  On Sat, Sep 17, 2016 at 12:09, lrishJoe<notifications@github.com> wrote:   
Thanks in advance for fixing, much appreciated!

**Comment by ryanjay0** [comment]
New release 0.84c fixes the issue.
