### ISSUE TITLE
Database.xml Transfer

### ISSUE THREAD

**Issue by Schoenherrr** [anlarke/MovieExplorer#40]
I was running 083j-64bit on my desktop. I installed 084c-64bit on my laptop. I assume rolling back will work, but wanted to see if there's a fix.

I copied over the database.xml. Hoping to keep all of the artwork I had manually input. The actual database seems to work fine. All of that artwork shows up.

When I restart the program the directories change back to match the original database, like the program isn't changing the .xml.

**Comment by ryanjay0** [comment]
For anyone reading this make sure to shut down the program before making changes to the db manually, or they will be overwritten when you shut it down.
